ikasaneip/component/converter/src/main/java/org/ikasan/component/converter/xml/ExceptionThrowingErrorListener.java
ikasaneip/component/converter/src/main/java/org/ikasan/component/converter/xml/TargetCreator.java
ikasaneip/component/converter/src/main/java/org/ikasan/component/converter/xml/ThreadLocalBeansWrapper.java
ikasaneip/component/converter/src/main/java/org/ikasan/component/converter/xml/XsltConverter.java
ikasaneip/component/converter/src/main/java/org/ikasan/component/converter/xml/XsltConverterConfiguration.java
ikasaneip/component/converter/src/main/java/org/ikasan/component/converter/xml/util/TransformationDataLookup.java
ikasaneip/component/converter/src/main/java/org/ikasan/component/converter/xml/util/XsltErrorUtils.java
ikasaneip/component/converter/src/main/java/org/ikasan/component/converter/xml/util/XsltUtils.java
ikasaneip/component/converter/src/test/java/org/ikasan/component/converter/xml/ExceptionThrowingErrorListenerTest.java
ikasaneip/component/converter/src/test/java/org/ikasan/component/converter/xml/XsltConverterTest.java
ikasaneip/component/converter/src/test/java/org/ikasan/component/converter/xml/util/XsltUtilsTest.java
ikasaneip/component/converter/src/test/resources/testXmlToText.xsl
ikasaneip/component/converter/src/test/resources/testXmlToXml.xsl
ikasaneip/component/validator/src/main/java/org/ikasan/component/validator/xml/ExceptionThrowingErrorHandler.java
ikasaneip/component/validator/src/main/java/org/ikasan/component/validator/xml/XMLValidator.java
ikasaneip/component/validator/src/main/java/org/ikasan/component/validator/xml/XMLValidatorConfiguration.java
ikasaneip/component/validator/src/test/java/org/ikasan/component/validator/xml/XMLValidatorTest.java

Changes for IKASAN-795  XsltConverter  IKASAN-797  XmlValidator

Ikasan 795 xslt converter

---

ikasaneip/platform/ikasan-setup/src/main/resources/providers-properties.xml

Fixed for H2 by using current_date function in SQL scripts

IKASAN-824 H2 scripts are using invalid getdate() function

---

ikasaneip/filetransfer/client-connection/pom.xml
ikasaneip/filetransfer/client-filetransfer/pom.xml
ikasaneip/filetransfer/common/pom.xml
ikasaneip/filetransfer/connector-base/pom.xml
ikasaneip/filetransfer/connector-basefiletransfer/pom.xml
ikasaneip/filetransfer/connector-filetransfer-parent/pom.xml
ikasaneip/filetransfer/connector-ftp/client/pom.xml
ikasaneip/filetransfer/connector-ftp/jar/pom.xml
ikasaneip/filetransfer/connector-ftp/pom.xml
ikasaneip/filetransfer/connector-ftp/rar/pom.xml
ikasaneip/filetransfer/pom.xml
ikasaneip/pom.xml
ikasaneip/sample/jboss/ftp/ear/pom.xml

Extract dependencies to dependencyManagement of a parent pom

IKASAN-826 -  Extract dependencies to dependencyManagement of a parent pom

---

ikasaneip/developer/mvn-archetype/ikasan-build-parent/pom.xml
ikasaneip/developer/mvn-archetype/ikasan-jboss-6/pom.xml
ikasaneip/developer/mvn-archetype/ikasan-rt-conf-jboss-6/pom.xml

- Add explicit dependency on the maven-plugin-plugin to see if this fixes compilation error on ec2 bamboo.

IKASAN-828: Fix bamboo build off master branch

---

ikasaneip/builder/spring/src/test/java/org/ikasan/builder/SampleMonitor.java
ikasaneip/module/pom.xml
ikasaneip/module/src/main/java/org/ikasan/module/service/ModuleInitialisationServiceImpl.java
ikasaneip/monitor/src/main/java/org/ikasan/monitor/DefaultMonitorImpl.java
ikasaneip/monitor/src/main/java/org/ikasan/monitor/MonitorFactoryImpl.java
ikasaneip/monitor/src/main/resources/monitor-service-conf.xml
ikasaneip/monitor/src/test/java/org/ikasan/monitor/DefaultMonitorImplTest.java
ikasaneip/monitor/src/test/java/org/ikasan/monitor/MonitorFactoryImplTest.java
ikasaneip/monitor/src/test/java/org/ikasan/monitor/notifier/EmailNotifierTest.java
ikasaneip/spec/monitor/src/main/java/org/ikasan/spec/monitor/Monitor.java

Tested OK with multiple stop/start/pause and redeploy scenarios

IKASAN-820 - allow executorService instances to be closed/destroyed

---

ikasaneip/compatibility/0.8.x/src/main/java/org/ikasan/compatibility/component/converter/JmsMapSinglePayloadTextConverter.java
ikasaneip/compatibility/0.8.x/src/test/java/org/ikasan/compatibility/component/converter/JmsMapSinglePayloadTextConverterTest.java

impl of missing MapMessage to String converter

IKASAN-841

---

.travis.yml

- Updated .travis.yml file however need login to travis to setup the
environment variables OSS_IKASAN_USER and OSS_IKASAN_PASS
Andrzej are you able to add these two environment variables to travis prior to pulling in the request ?

IKASAN-853 Allow deployment of snapshots to oss by travis

---

ikasaneip/dashboard/sql/sybase/SecurityPolicy2015-06-21 20-14-36.sql
ikasaneip/dashboard/sql/sybase/create-hospitalServiceTables.sql
ikasaneip/dashboard/war/src/main/java/org/ikasan/dashboard/ui/IkasanUI.java
ikasaneip/dashboard/war/src/main/java/org/ikasan/dashboard/ui/mappingconfiguration/panel/MappingConfigurationSearchPanel.java
ikasaneip/platform/ikasan-setup/src/main/java/org/ikasan/setup/persistence/service/PersistenceServiceImpl.java
ikasaneip/platform/ikasan-setup/src/main/resources/providers-properties.xml
ikasaneip/platform/ikasan-setup/src/test/java/org/ikasan/setup/persistence/service/PersistenceServiceImplTest.java
ikasaneip/security/src/main/java/org/ikasan/security/service/LdapServiceImpl.java
ikasaneip/topology/src/main/resources/org/ikasan/topology/model/Component.hbm.xml

Added table to set up project. Please merge back to trunk.

IKASAN-780 Added outstanding tables to setup module. General tidy up.

---

ikasaneip/platform/ikasan-eip-test/pom.xml
ikasaneip/pom.xml

Cleaning up minor annoyances IKASAN-914, for eclipse developers, IKASAN-915 missing ikasan-eip-test dependency.

Ikasan 914 - Clean up minor annoyances

---

ikasaneip/compatibility/0.8.x/src/main/java/org/ikasan/compatibility/component/converter/JmsMapSinglePayloadTextConverter.java
ikasaneip/compatibility/0.8.x/src/test/java/org/ikasan/compatibility/component/converter/JmsMapSinglePayloadTextConverterTest.java

fix the conversion (getBytes to String)

IKASAN-916

---

ikasaneip/webconsole/war/src/main/webapp/WEB-INF/security-service-conf.xml

/WEB-INF/security-service-conf.xml - remove ` sign

IKASAN-918 - fix typo in  /WEB-INF/security-service-conf.xml

---

ikasaneip/configuration-service/src/main/java/org/ikasan/configurationService/service/ConfiguredResourceConfigurationService.java
ikasaneip/configuration-service/src/test/java/org/ikasan/configurationService/service/ConfiguredResourceConfigurationServiceTest.java
ikasaneip/configuration-service/src/test/java/org/ikasan/configurationService/service/SampleConfiguration.java

Fixed another but with the ConfigurationService

IKASAN-924: ConfiguredResoureConfigurationService failing on update of

---

ikasaneip/spec/uber/pom.xml

- Added createSourcesJar to uber pom

ISSUE-945: Uber spec jar missing sources

---

ikasaneip/component/endpoint/email-endpoint/pom.xml
ikasaneip/component/endpoint/email-endpoint/src/main/java/org/ikasan/component/endpoint/email/producer/DefaultEmailPayload.java
ikasaneip/component/endpoint/email-endpoint/src/main/java/org/ikasan/component/endpoint/email/producer/EmailPayload.java
ikasaneip/component/endpoint/email-endpoint/src/main/java/org/ikasan/component/endpoint/email/producer/EmailProducer.java
ikasaneip/component/endpoint/email-endpoint/src/main/java/org/ikasan/component/endpoint/email/producer/EmailProducerConfiguration.java
ikasaneip/component/endpoint/email-endpoint/src/test/java/org/ikasan/component/endpoint/email/producer/EmailProducerTest.java

changes after reviewing comments
1. added license
2. extracted library version as properties
3. implemented managed resource for producer
4. added mail server failure test

IKASAN-981 Add email end point.

---

ikasaneip/builder/spring/src/main/java/org/ikasan/builder/FlowFactory.java

you dont have to explicitly wire this each time
- Was due to FlowFactory autowiring not working and the
ApplicationContextAware setApplicationContext was used to wire up the
service beans methods instead. Was just a case of adding the serialiser
lookup in the setApplicationContext() method.
- Removed autowiring annotations as werent working

IKASAN-980 Default FlowFactory to using the IkasanSerialiserFactory so

---

ikasaneip/pom.xml

Revert "Upgrade plugins, make Java 8 compatible"

---

ikasaneip/filter/pom.xml
ikasaneip/filter/src/main/java/org/ikasan/filter/duplicate/dao/FilteredMessageDao.java
ikasaneip/filter/src/main/java/org/ikasan/filter/duplicate/dao/HibernateFilteredMessageDaoImpl.java
ikasaneip/filter/src/main/java/org/ikasan/filter/duplicate/service/DefaultDuplicateFilterService.java
ikasaneip/filter/src/main/java/org/ikasan/filter/duplicate/service/FilteredMessageConfiguration.java
ikasaneip/filter/src/test/java/org/ikasan/filter/duplicate/dao/FilteredMessageDaoInMemDBTest.java
ikasaneip/spec/service/management/src/main/java/org/ikasan/spec/management/HousekeeperService.java
ikasaneip/system-event/src/main/java/org/ikasan/systemevent/dao/HibernateSystemEventDao.java
ikasaneip/system-event/src/main/java/org/ikasan/systemevent/dao/SystemEventDao.java
ikasaneip/wiretap/src/main/java/org/ikasan/wiretap/dao/HibernateWiretapDao.java
ikasaneip/wiretap/src/main/java/org/ikasan/wiretap/dao/WiretapDao.java
ikasaneip/wiretap/src/test/java/org/ikasan/wiretap/dao/HibernateWiretapDaoTest.java

for wiretaps, systemEvents and messageFilters

IKASAN-1110 Add parametrised housekeeping query 

---

ikasaneip/filter/src/main/java/org/ikasan/filter/duplicate/dao/FilteredMessageDao.java
ikasaneip/filter/src/main/java/org/ikasan/filter/duplicate/dao/HibernateFilteredMessageDaoImpl.java
ikasaneip/filter/src/main/java/org/ikasan/filter/duplicate/service/DefaultDuplicateFilterService.java
ikasaneip/filter/src/main/java/org/ikasan/filter/duplicate/service/FilteredMessageConfiguration.java
ikasaneip/filter/src/test/java/org/ikasan/filter/duplicate/dao/FilteredMessageDaoInMemDBTest.java
ikasaneip/system-event/src/main/java/org/ikasan/systemevent/dao/HibernateSystemEventDao.java
ikasaneip/system-event/src/main/java/org/ikasan/systemevent/dao/SystemEventDao.java
ikasaneip/system-event/src/test/java/org/ikasan/systemevent/dao/HibernateSystemEventDaoTest.java
ikasaneip/wiretap/src/main/java/org/ikasan/wiretap/dao/HibernateWiretapDao.java
ikasaneip/wiretap/src/main/java/org/ikasan/wiretap/dao/WiretapDao.java
ikasaneip/wiretap/src/test/java/org/ikasan/wiretap/dao/HibernateWiretapDaoTest.java

Add parametrised housekeeping query for systemEvents and messageFilters, besides wiretaps

IKASAN-1110  Add parametrised housekeeping query

---

ikasaneip/developer/mvn-archetype/jboss-6-module-activemq/src/main/resources/archetype-resources/cli/activemq-resource-adapter.sh

Update CLI script with extra UseSessionArgs property to ensure transactionality

Update CLI script with extra UseSessionArgs property to ensure transactionality

---

ikasaneip/developer/mvn-archetype/jboss-6-module-activemq/src/main/resources/archetype-resources/cli/activemq-resource-adapter.sh

Update CLI resource adapter with extra UseSessionArgs=flag to ensure transactionality

Update CLI resource adapter with extra UseSessionArgs=flag

---

ikasaneip/filetransfer/connector-ftp/client/src/main/java/org/ikasan/endpoint/ftp/producer/FtpProducer.java
ikasaneip/filetransfer/connector-ftp/client/src/test/java/org/ikasan/endpoint/ftp/producer/FtpProducerTest.java
ikasaneip/filetransfer/connector-sftp/client/src/main/java/org/ikasan/endpoint/sftp/producer/SftpProducer.java
ikasaneip/filetransfer/connector-sftp/client/src/test/java/org/ikasan/endpoint/sftp/producer/SftpProducerTest.java

IKASAN-1218 - Enhance Ikasan FtpProducer and SftpProducer for Directory Creation

Ikasan 1218 1.3.x

---

ikasaneip/filetransfer/connector-ftp/client/src/main/java/org/ikasan/endpoint/ftp/producer/FtpProducer.java
ikasaneip/filetransfer/connector-ftp/client/src/test/java/org/ikasan/endpoint/ftp/producer/FtpProducerTest.java
ikasaneip/filetransfer/connector-sftp/client/src/main/java/org/ikasan/endpoint/sftp/producer/SftpProducer.java
ikasaneip/filetransfer/connector-sftp/client/src/test/java/org/ikasan/endpoint/sftp/producer/SftpProducerTest.java

IKASAN-1218 - Enhance Ikasan FtpProducer and SftpProducer for Directory Creation

Ikasan 1218 2.0.x

---

ikasaneip/wiretap/src/test/java/org/ikasan/history/service/MessageHistoryServiceImplTest.java

(cherry picked from commit 5a474af)
(cherry picked from commit 9859188)

Fix failing wiretap tests

---

ikasaneip/module/pom.xml
ikasaneip/module/src/main/java/org/ikasan/module/container/ModuleContainerImpl.java
ikasaneip/module/src/main/java/org/ikasan/module/service/ModuleInitialisationServiceImpl.java
ikasaneip/module/src/test/java/org/ikasan/module/service/ModuleInitialisationServiceImplTest.java
ikasaneip/spec/module/src/main/java/org/ikasan/spec/module/ModuleContainer.java
ikasaneip/wiretap/src/test/java/org/ikasan/history/service/MessageHistoryServiceImplTest.java

IKASAN-1268 - Add remove functionality to ModuleContainer and ensure module is removed on destroy

IKASAN-1268 - Add remove functionality to ModuleContainer and ensure module is removed on destroy

---

ikasaneip/builder/jar/src/main/java/org/ikasan/builder/BuilderFactoryImpl.java
ikasaneip/builder/jar/src/main/java/org/ikasan/builder/ExceptionResolverBuilder.java
ikasaneip/builder/jar/src/main/java/org/ikasan/builder/ExceptionResolverBuilderImpl.java
ikasaneip/builder/jar/src/main/java/org/ikasan/builder/FlowBuilder.java
ikasaneip/builder/jar/src/main/java/org/ikasan/builder/OnException.java
ikasaneip/builder/jar/src/main/java/org/ikasan/builder/component/ComponentBuilder.java
ikasaneip/builder/jar/src/main/java/org/ikasan/builder/component/ScheduledConsumerBuilderImpl.java
ikasaneip/builder/jar/src/main/java/org/ikasan/builder/component/endpoint/JmsConsumerBuilder.java
ikasaneip/builder/jar/src/main/java/org/ikasan/builder/component/endpoint/JmsConsumerBuilderImpl.java
ikasaneip/builder/jar/src/main/java/org/ikasan/builder/component/endpoint/JmsProducerBuilder.java
ikasaneip/builder/jar/src/main/java/org/ikasan/builder/component/endpoint/JmsProducerBuilderImpl.java
ikasaneip/builder/jar/src/main/java/org/ikasan/builder/component/endpoint/ScheduledConsumerBuilder.java
ikasaneip/builder/jar/src/main/java/org/ikasan/builder/component/endpoint/ScheduledConsumerBuilderImpl.java
ikasaneip/builder/jar/src/main/java/org/ikasan/builder/component/filter/MessageFilterBuilder.java
ikasaneip/builder/jar/src/main/java/org/ikasan/builder/component/filter/MessageFilterBuilderImpl.java
ikasaneip/builder/jar/src/test/java/org/ikasan/builder/ExceptionResolverBuilderImplTest.java
ikasaneip/builder/jar/src/test/java/org/ikasan/builder/FlowBuilderTest.java
ikasaneip/builder/jar/src/test/java/org/ikasan/builder/component/ComponentBuilderTest.java
ikasaneip/builder/jar/src/test/java/org/ikasan/builder/component/endpoint/JmsConsumerBuilderTest.java
ikasaneip/builder/jar/src/test/java/org/ikasan/builder/component/endpoint/JmsProducerBuilderTest.java
ikasaneip/builder/jar/src/test/java/org/ikasan/builder/component/endpoint/ScheduledConsumerBuilderTest.java
ikasaneip/builder/jar/src/test/java/org/ikasan/builder/component/filter/MessageFilterBuilderImplTest.java

2.0.x Ikasan-1279 refactor

---

ikasaneip/component/endpoint/jms-spring-arjuna/src/main/java/org/ikasan/component/endpoint/jms/spring/listener/ArjunaIkasanMessageListenerContainer.java

ikasan-1293 - JMS IM using ArjunaIkasanMessageListenerContainer not enlist to XA transaction

2.0.x ikasan-1293

---

ikasaneip/component/validator/src/test/java/org/ikasan/component/validator/schematron/SchematronValidatorTest.java
ikasaneip/configuration-service/pom.xml
ikasaneip/configuration-service/src/main/java/org/ikasan/configurationService/util/ConfigurationCreationHelper.java
ikasaneip/pom.xml
ikasaneip/replay/pom.xml
ikasaneip/replay/src/main/java/org/ikasan/replay/service/ReplayServiceImpl.java
ikasaneip/replay/src/test/java/org/ikasan/replay/service/ReplayServiceTest.java
ikasaneip/sample/spring-boot/ftp/src/main/resources/overwriteDBCreation.sql
ikasaneip/sample/spring-boot/jms/src/main/resources/overwriteDBCreation.sql
ikasaneip/sample/spring-boot/sftp/src/main/resources/overwriteDBCreation.sql
ikasaneip/topology/pom.xml
ikasaneip/topology/src/main/java/org/ikasan/topology/service/TopologyServiceImpl.java

IKASAN-1294 - Get rid off Jersey dependencies on replay and topology configuration-service and projects

2.0.x IKASAN-1294

---

ikasaneip/builder/jar/src/main/java/org/ikasan/builder/DefaultSpringBootIkasanApplication.java
ikasaneip/builder/jar/src/main/java/org/ikasan/builder/IkasanApplicationFactory.java
ikasaneip/builder/jar/src/main/java/org/ikasan/builder/IkasanApplicationSpringBoot.java

(cherry picked from commit d4d1e37)

IKASAN-1279 - builder pattern implementation

---

ikasaneip/dashboard/war/pom.xml
ikasaneip/pom.xml
ikasaneip/sample/spring-boot/file/pom.xml
ikasaneip/sample/spring-boot/file/src/main/resources/datasource-conf.xml
ikasaneip/sample/spring-boot/file/src/main/resources/jbossts-properties.xml
ikasaneip/webconsole/jar/src/main/resources/security-service-boot-conf.xml

Add explicit pointcut on WiretapDao.save method to ensure that wiretap enlist to XA transaction.
Refactoring of spring-boot-file datasources.

IKASAN-1300 -  Wiretaps not being captured as DB wiretaps

---

ikasaneip/dashboard/war/src/main/java/org/ikasan/dashboard/ui/Menu.java.orig
ikasaneip/dashboard/war/src/main/java/org/ikasan/dashboard/ui/administration/panel/GroupSelectPanel.java
ikasaneip/dashboard/war/src/main/java/org/ikasan/dashboard/ui/administration/panel/RolePanel.java
ikasaneip/dashboard/war/src/main/java/org/ikasan/dashboard/ui/administration/window/GroupSelectWindow.java
ikasaneip/wiretap/src/main/java/org/ikasan/history/dao/HibernateMessageHistoryDao.java
ikasaneip/wiretap/src/test/java/org/ikasan/history/dao/HibernateMessageHistoryDaoTest.java

This PR is to bring in missing channges from master branch. That will avoid later conflicts when merging 2.0.x to master.

2.0.x  <- master branch  catch up

---

ikasaneip/platform/ikasan-eip-standalone/pom.xml
ikasaneip/pom.xml
ikasaneip/sample/spring-boot/builder-pattern/pom.xml
ikasaneip/sample/spring-boot/builder-pattern/src/main/resources/application.properties
ikasaneip/sample/spring-boot/builder-pattern/src/main/resources/datasource-conf.xml
ikasaneip/sample/spring-boot/builder-pattern/src/test/resources/application.properties
ikasaneip/sample/spring-boot/file/src/main/resources/application.properties
ikasaneip/sample/spring-boot/file/src/main/resources/datasource-conf.xml
ikasaneip/sample/spring-boot/file/src/test/resources/application.properties
ikasaneip/sample/spring-boot/ftp/pom.xml
ikasaneip/sample/spring-boot/ftp/src/main/resources/application.properties
ikasaneip/sample/spring-boot/ftp/src/main/resources/datasource-conf.xml
ikasaneip/sample/spring-boot/ftp/src/test/resources/application.properties
ikasaneip/sample/spring-boot/jms/pom.xml
ikasaneip/sample/spring-boot/jms/src/main/java/org/ikasan/sample/spring/boot/builderpattern/ExceptionGenerationgBroker.java
ikasaneip/sample/spring-boot/jms/src/main/java/org/ikasan/sample/spring/boot/builderpattern/ModuleConfig.java
ikasaneip/sample/spring-boot/jms/src/main/java/org/ikasan/sample/spring/boot/builderpattern/SampleGeneratedException.java
ikasaneip/sample/spring-boot/jms/src/main/resources/application.properties
ikasaneip/sample/spring-boot/jms/src/main/resources/datasource-conf.xml
ikasaneip/sample/spring-boot/jms/src/main/resources/exception-conf.xml
ikasaneip/sample/spring-boot/jms/src/test/java/org/ikasan/sample/spring/boot/builderpattern/ApplicationTest.java
ikasaneip/sample/spring-boot/jms/src/test/resources/application.properties
ikasaneip/sample/spring-boot/sftp/pom.xml
ikasaneip/sample/spring-boot/sftp/src/main/resources/application.properties
ikasaneip/sample/spring-boot/sftp/src/main/resources/datasource-conf.xml
ikasaneip/sample/spring-boot/sftp/src/test/resources/application.properties
ikasaneip/webconsole/jar/src/main/resources/security-service-boot-conf.xml

spring-boot samples were enhanced:
- align datasource-conf.xml 
- use H2 XADatasource
- add spring acurator dependency to allow springboot  rest services

2.0.x DB samples  enhancements 

---

ikasaneip/component/endpoint/email-endpoint/src/test/java/org/ikasan/component/endpoint/email/producer/EmailProducerTest.java
ikasaneip/sample/spring-boot/builder-pattern/src/test/java/org/ikasan/sample/spring/boot/builderpattern/MyApplicationTest.java
ikasaneip/sample/spring-boot/builder-pattern/src/test/resources/application.properties
ikasaneip/sample/spring-boot/file/src/test/java/com/ikasan/sample/spring/boot/builderpattern/ApplicationTest.java
ikasaneip/sample/spring-boot/file/src/test/resources/application.properties
ikasaneip/sample/spring-boot/ftp/src/test/java/org/ikasan/sample/spring/boot/builderpattern/ApplicationTest.java
ikasaneip/sample/spring-boot/ftp/src/test/resources/application.properties
ikasaneip/sample/spring-boot/jms/src/main/java/org/ikasan/sample/spring/boot/builderpattern/ModuleConfig.java
ikasaneip/sample/spring-boot/jms/src/test/java/org/ikasan/sample/spring/boot/builderpattern/ApplicationTest.java
ikasaneip/sample/spring-boot/jms/src/test/java/org/ikasan/sample/spring/boot/builderpattern/ModuleTestConfig.java
ikasaneip/sample/spring-boot/jms/src/test/resources/application.properties
ikasaneip/sample/spring-boot/sftp/src/test/java/org/ikasan/sample/spring/boot/builderpattern/ApplicationTest.java
ikasaneip/sample/spring-boot/sftp/src/test/resources/application.properties

After Number of attempts I believe I managed to refactor the test in a way so that they dont clash. Test which are using activemq embeded broker are using different broker name and run on different random port.

2.0.x ikasan 1324 - fix randomly failing JMS spring-boot sample test

---

ikasaneip/module/src/main/java/org/ikasan/module/service/MissingBeanConfigurationException.java
ikasaneip/module/src/main/java/org/ikasan/module/service/MissingConfigFileException.java
ikasaneip/module/src/main/java/org/ikasan/module/service/MissingPropertiesException.java
ikasaneip/module/src/main/java/org/ikasan/module/service/ModuleInitialisationServiceImpl.java
ikasaneip/rest-boot/src/main/java/org/ikasan/rest/module/DiscoveryApplication.java
ikasaneip/rest-boot/src/main/java/org/ikasan/rest/module/ModuleControlApplication.java
ikasaneip/rest/src/main/java/org/ikasan/rest/discovery/DiscoveryApplication.java
ikasaneip/topology/src/main/java/org/ikasan/topology/model/Flow.java
ikasaneip/topology/src/test/java/org/ikasan/topology/model/ModuleTest.java

This merge is to:
- topology service discovery method
- enhance error handling of moduleInitialisatioservice to expose missing beans and properties rather then fail silently 
@el-git could you review?

2.0.x ikasan 1358 - topology service fixes 

---

ikasaneip/security/src/main/java/org/ikasan/security/service/authentication/CustomAuthenticationProvider.java
ikasaneip/security/src/main/java/org/ikasan/security/service/authentication/IkasanAuthentication.java
ikasaneip/webconsole/jar/src/main/resources/security-service-boot-conf.xml

IKASAN-1369 - Add CustomAuthenticationProvider and add it as additional authentication provider to standalone IM

IKASAN-1369 - Add CustomAuthenticationProvider 

---

ikasaneip/serialiser/src/main/java/org/ikasan/serialiser/model/JmsMessageDefaultImpl.java
ikasaneip/serialiser/src/test/java/org/ikasan/serialiser/converter/JmsTextMessageConverterTest.java

…wire the replayRecordService.

IKASAN-1393 - BugFix on Serialisation of JMS based models

---

ikasaneip/dashboard/boot/pom.xml
ikasaneip/dashboard/war/pom.xml

(cherry picked from commit 3c70293)

IKASAN-1411 updating vaadin charts license

---

ikasaneip/builder/jar/src/main/java/org/ikasan/builder/component/endpoint/FileConsumerBuilderImpl.java
ikasaneip/builder/jar/src/main/java/org/ikasan/builder/component/endpoint/JmsConsumerBuilder.java
ikasaneip/builder/jar/src/main/java/org/ikasan/builder/component/endpoint/JmsConsumerBuilderImpl.java
ikasaneip/builder/jar/src/main/java/org/ikasan/builder/component/endpoint/JmsProducerBuilder.java
ikasaneip/builder/jar/src/main/java/org/ikasan/builder/component/endpoint/JmsProducerBuilderImpl.java
ikasaneip/builder/jar/src/test/java/org/ikasan/builder/component/endpoint/JmsProducerBuilderTest.java

Ikasan-1427 - Provide credentials on each connection to the JMS provider;
Ikasan-1428 - Ensure FileConsumerConfiguration is set if not specified by the developer on the builder;

2.0.1 ikasan 1427 bug fix on jms connection authentication; IKASAN-1428 bug fix on FileConsumerConfiguration

---

ikasaneip/component/endpoint/filetransfer/common/src/main/java/org/ikasan/filetransfer/Payload.java
ikasaneip/component/endpoint/filetransfer/common/src/main/java/org/ikasan/filetransfer/component/DefaultPayload.java
ikasaneip/component/endpoint/filetransfer/common/src/main/java/org/ikasan/filetransfer/component/FilePayload.java
ikasaneip/component/endpoint/filetransfer/common/src/main/java/org/ikasan/filetransfer/util/ChecksumUtils.java
ikasaneip/component/endpoint/filetransfer/common/src/main/java/org/ikasan/filetransfer/util/checksum/ChecksumSupplier.java
ikasaneip/component/endpoint/filetransfer/common/src/main/java/org/ikasan/filetransfer/util/checksum/Md5ChecksumSupplier.java
ikasaneip/component/endpoint/filetransfer/connector-base/src/main/java/org/ikasan/connector/BaseFileTransferConnection.java
ikasaneip/component/endpoint/filetransfer/connector-basefiletransfer/src/main/java/org/ikasan/connector/basefiletransfer/outbound/BaseFileTransferConnectionImpl.java
ikasaneip/component/endpoint/filetransfer/connector-basefiletransfer/src/main/java/org/ikasan/connector/basefiletransfer/outbound/command/AbstractBaseFileTransferTransactionalResourceCommand.java
ikasaneip/component/endpoint/filetransfer/connector-basefiletransfer/src/main/java/org/ikasan/connector/basefiletransfer/outbound/command/ChecksumDeliveredCommand.java
ikasaneip/component/endpoint/filetransfer/connector-basefiletransfer/src/main/java/org/ikasan/connector/basefiletransfer/outbound/command/ChecksumValidatorCommand.java
ikasaneip/component/endpoint/filetransfer/ftp/src/main/java/org/ikasan/connector/ftp/outbound/FTPConnectionImpl.java
ikasaneip/component/endpoint/filetransfer/ftp/src/main/java/org/ikasan/endpoint/ftp/FileTransferConnectionTemplate.java
ikasaneip/component/endpoint/filetransfer/ftp/src/main/java/org/ikasan/endpoint/ftp/producer/FtpProducer.java
ikasaneip/component/endpoint/filetransfer/ftp/src/test/java/org/ikasan/endpoint/ftp/producer/FtpProducerTest.java
ikasaneip/component/endpoint/filetransfer/sftp/src/main/java/org/ikasan/connector/sftp/outbound/SFTPConnectionImpl.java
ikasaneip/component/endpoint/filetransfer/sftp/src/main/java/org/ikasan/endpoint/sftp/FileTransferConnectionTemplate.java
ikasaneip/component/endpoint/filetransfer/sftp/src/main/java/org/ikasan/endpoint/sftp/producer/SftpProducer.java
ikasaneip/component/endpoint/filetransfer/sftp/src/test/java/org/ikasan/connector/sftp/net/SFTPClientTest.java
ikasaneip/component/endpoint/filetransfer/sftp/src/test/java/org/ikasan/connector/sftp/outbound/SFTPManagedConnectionOpenSessionTest.java
ikasaneip/component/endpoint/filetransfer/sftp/src/test/java/org/ikasan/connector/sftp/ssh/SftpServerWithPublickeyAuthenticator.java
ikasaneip/component/endpoint/filetransfer/sftp/src/test/java/org/ikasan/endpoint/sftp/producer/SftpProducerTest.java
ikasaneip/component/endpoint/filetransfer/sftp/src/test/resources/data/test-data.xml
ikasaneip/pom.xml
ikasaneip/test/src/main/java/org/ikasan/testharness/flow/jms/MessageListenerVerifier.java

I have been fairly brutal with deprecating methods on the payload object. Please let me know if you do not think a method should be deprecated.

IKASAN-1511 - File transfer streams - to support large FTP/SFTP payloads without chunking

---

ikasaneip/dashboard/boot/src/main/resources/application.properties

Ikasan dashboard does not startup due to org.ikasan.builder.IkasanBaseAutoConfiguration

IKASAN-1513 -  Ikasan dashboard does not load due to IkasanBaseAutoConfiguration

---

ikasaneip/dashboard/boot/src/main/resources/application.properties
ikasaneip/dashboard/jar/pom.xml
ikasaneip/dashboard/jar/src/main/java/org/ikasan/dashboard/ui/Menu.java
ikasaneip/dashboard/jar/src/main/java/org/ikasan/dashboard/ui/framework/data/LoginFieldGroup.java

IKASAN-1539 removing noise on start up. Removing the dashboard icon from the menu and fixing DB setup message.

IKASAN-1539 removing noise on start up. Removing the dashboard icon from the menu and fixing DB setup message.

---

ikasaneip/platform/ikasan-setup/src/main/resources/db-changelog-2.1.0.xml
ikasaneip/platform/ikasan-setup/src/main/resources/db/index/db-changeLog-createIndexMetricEventEventId.xml

A new index on EventId column in MetricEvent table.

IKASAN-1523
